EnvSettings:
  env: "local" # local, prod

postgres:
  host: "localhost"
  port: 5432
  user: "contester"
  password: "contester_pass"  # Do NOT track this by git in real projects
  dbname: "example_database"

ServerSettings:
  port: 8000
  secure_port: 6653
