EnvSettings:
  env: "local" # local, prod

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "STORED_SOMEWHERE_ELSE"  # Do NOT track this by git in real projects
  dbname: "PROJECT_NAME"

ServerSettings:
  port: 8000
  secure_port: 6653
